name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: haskell:8.10

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: stack build --only-dependencies
    - name: Test
      run: stack test
    - name: Copy binary to .github
      run: find .stack-work -name mat-chalmers -type f -exec mv '{}' .github/mat-chalmers-linux-x86_64 ';'
    - uses: actions/upload-artifact@master
      if: "github.ref == 'refs/heads/master'"
      with:
        name: mat-chalmers
        path: .github/mat-chalmers-linux-x86_64
